language: cpp
matrix:
  include:
    - dist: trusty
      compiler: gcc
      env:
        - USE_WEBVIEW=OFF
        - WX_PKG_NAME=libwxgtk3.0-0
    - dist: xenial
      compiler: gcc
      env:
        - USE_WEBVIEW=ON
        - WX_PKG_NAME=libwxgtk3.0-0v5
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get --allow-unauthenticated install $WX_PKG_NAME libwxgtk3.0-dev libgps-dev libglu1-mesa-dev libgtk2.0-dev libbz2-dev libtinyxml-dev libportaudio2 portaudio19-dev libcurl4-openssl-dev libexpat1-dev libcairo2-dev libarchive-dev liblzma-dev libexif-dev libsqlite3-dev libelf-dev gettext; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] && [[ "$USE_WEBVIEW" == "ON" ]]; then sudo apt-get --allow-unauthenticated install libwxgtk-webview3.0-dev libgtk-3-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo libexif xz libarchive;
    wget http://opencpn.navnux.org/build_deps/wx312_opencpn50_macos109.tar.xz; tar xJf
    wx312_opencpn50_macos109.tar.xz -C /tmp; export PATH="/usr/local/opt/gettext/bin:$PATH";  echo
    'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile; fi
script:
  - ./travisci_build.sh
before_deploy:
  - openssl aes-256-cbc -K $encrypted_831747f1d3db_key -iv $encrypted_831747f1d3db_iv  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scp -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null $TRAVIS_BUILD_DIR/build/*.dmg travis@ocpnci.kalian.cz:files/; fi
  on:
    branch: master
    tags: false
notifications:
  email: false
git:
  depth: 10
